before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

#cache:
#  paths:
#    - .gradle

stages:
  - build
  - test

build:
  stage: build
  script:
#   you can use ./gradlew build -x test  as well
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test