before_script:
  - cd API/
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

cache:
  paths:
    - ./API/.gradle/wrapper
    - ./API/.gradle/caches

stages:
  - api-build
  - run-docker-containers
  - test
  - deploy
  - stop-docker-containers

api-build:
  stage: api-build
  script:
    - ./gradlew assemble

run-docker-containers:
  stage: run-docker-containers
  needs: ["api-build"]
  script:
    - ./gradlew build
    # - docker rm -f $(docker ps -aq)
    - sudo docker-compose up --build -d    

api-test:
  stage: test
  needs: ["api-build"]
  script:
    - ./gradlew test

sonarqube-check:
  stage: test
  needs: ["api-build"]
  image: gradle:jre11-slim
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
    GIT_DEPTH: "0"  
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: ./gradlew sonarqube
  allow_failure: true
  only:
    - main 

cypress:
  image: node:latest
  stage: test
  needs: ["run-docker-containers"]
  before_script:
    - cd Frontend/
    - sudo docker exec -i footballtix_db_1 mysql -u root -proot < ./cypress/testdb.sql
    - npm install
  script:
    - npm run cypress

push-to-dockerhub:
  stage: deploy
  needs: ["run-docker-containers", "api-test"]
  before_script:
    - sudo docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - sudo docker commit footballtix_footballtix-frontend_1 stoyank7/footballtix:frontend
    - sudo docker push stoyank7/footballtix:frontend
    - sudo docker commit footballtix_footballtix-api_1 stoyank7/footballtix:api
    - sudo docker push stoyank7/footballtix:api
    - sudo docker commit footballtix_db_1 stoyank7/footballtix:db
    - sudo docker push stoyank7/footballtix:db

stop-docker-containers:
  stage: stop-docker-containers
  when: always
  script:
    - sudo docker-compose down