before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew build -x test

test:
  stage: test
  script:
    - ./gradlew test