before_script:
  - cd API/
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

cache:
  paths:
    - ./API/.gradle/wrapper
    - ./API/.gradle/caches

stages:
  # - build
  # - test
  # - sonarqube
  - run
  - cypress

# build:
#   stage: build
#   script:
#     - ./gradlew assemble

# test:
#   stage: test
#   script:
#     - ./gradlew test

# sonarqube-check:
#   stage: sonarqube
#   image: gradle:jre11-slim
#   variables:
#     SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
#     GIT_DEPTH: "0"  
#   cache:
#     key: "${CI_JOB_NAME}"
#     paths:
#       - .sonar/cache
#   script: ./gradlew sonarqube
#   allow_failure: true
#   only:
#     - main 

run:
  stage: run
  script:
    - ./gradlew build
    - pwd
    - ls
    # - docker rm -f $(docker ps -aq)
    - docker-compose up --build

cypress:
  image: node:latest
  stage: cypress
  script:
    - cd /Frontend
    - npm run cypress


#deploy to dockerhub