before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export GRADLE_USER_HOME=cache/.gradle
  - chmod +x ./gradlew

variables:
  MAVEN_REPO: /cache/.m2
  GRADLE_USER_HOME: /cache/.gradle

cache:
  paths:
    - .gradle

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew build -x test

test:
  stage: test
  script:
    - ./gradlew test