version: "3.3"
services:
  api:
    container_name: api
    build:
      context: API
      dockerfile: Dockerfile
      args:
        JAR_FILE: build/libs/footballtix-0.0.2.jar
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    networks:
      - frontend
      - backend

  frontend:
    container_name: frontend
    build:
      context: Frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_ENDPOINT: ${REACT_APP_API_ENDPOINT}
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - api
    networks:
      - frontend

  db:
    container_name: db
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: footballtix
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - backend

volumes:
  dbdata: null

networks:
  backend: null
  frontend: null
