FROM azul/zulu-openjdk-alpine:11 

RUN addgroup -S spring && adduser -S spring -G spring

USER spring:spring

ARG JAR_FILE=target/*.jar

ARG EXPECTED_ORIGIN

RUN sh create-env-file.sh EXPECTED_ORIGIN=$EXPECTED_ORIGIN

COPY ${JAR_FILE} /app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","/app.jar"]